// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * @readonly
 * @enum {number}
 */
export const Direction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Next: 0,
    Previous: 1,
};

/**
 * Used to make sure webview2 bridge doesn't get overloaded.
 * 
 * Has to be json tagged to translate into JS
 */
export class SimplePackageListing {
    /**
     * Creates a new SimplePackageListing instance.
     * @param {Partial<SimplePackageListing>} [$$source = {}] - The source object to create the SimplePackageListing.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimplePackageListing instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SimplePackageListing}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SimplePackageListing(/** @type {Partial<SimplePackageListing>} */($$parsedSource));
    }
}
