// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Download(arg1:string):Promise<string>;

export function GetDownloadURL(arg1:api.PackageListing):Promise<string>;

export function GetTotalItems():Promise<number>;

export function Return10Listings(arg1:number,arg2:number):Promise<Array<api.PackageListing>>;
