// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function FilterMods(arg1) {
  return window['go']['main']['App']['FilterMods'](arg1);
}

export function GetDownloadURL(arg1) {
  return window['go']['main']['App']['GetDownloadURL'](arg1);
}

export function GetTotalItems() {
  return window['go']['main']['App']['GetTotalItems']();
}

export function Return10Listings(arg1, arg2) {
  return window['go']['main']['App']['Return10Listings'](arg1, arg2);
}

export function Return10Simple(arg1, arg2) {
  return window['go']['main']['App']['Return10Simple'](arg1, arg2);
}

export function Return10WithSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Return10WithSearch'](arg1, arg2, arg3);
}
