name: main

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
        #   {name: LethalModder, platform: linux/amd64, os: ubuntu-latest},
          {name: LethalModder, platform: windows/amd64, os: windows-latest, wails: wails3.exe},
        #   {name: LethalModder, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

    # Experiment to avoid downloading like 500 deps everytime
      - name: Cache go install artifacts
        id: cache-go-install
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/go/bin/
          key: ${{ runner.os }}-wails-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-install-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.6

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

    #   - run: go run github.com/tc-hib/go-winres@latest make --product-version=git-tag --file-version=git-tag

    #   - uses: dAppServer/wails-build-action@v2.2
    #     with:
    #       build-name: ${{ matrix.build.name }}
    #       build-platform: ${{ matrix.build.platform }}
    #       package: true
    #       go-version: 1.21

      - name: Set up Wails
        if: steps.cache-go-install.outputs.cache-hit != 'true'
        run: |
            go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Wails doctor for debug
        run: wails3 doctor

    # Need to adapt this to use wails3
      - name: Build windows/amd64
        run: |
            wails3 task build:windows:prod:amd64
            wails3 task package:windows:amd64

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{matrix.build.name}}
          path: |
            ${{ github.workspace }}LethalModder/LethalModder/bin/*
            ${{ github.workspace }}*\bin\*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*
          generate_release_notes: true
