name: main

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
        #   {name: LethalModder, platform: linux/amd64, os: ubuntu-latest},
          {name: LethalModder-windows, platform: windows/amd64, os: windows-latest},
        #   {name: LethalModder, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

    #   - run: go run github.com/tc-hib/go-winres@latest make --product-version=git-tag --file-version=git-tag

    #   - uses: dAppServer/wails-build-action@v2.2
    #     with:
    #       build-name: ${{ matrix.build.name }}
    #       build-platform: ${{ matrix.build.platform }}
    #       package: true
    #       go-version: 1.21

      - name: Set up wailsv3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

    # Need to adapt this to use wails3
      - name: Build windows/amd64
        run: |
            wails3 task build:windows:prod:amd64
            wails3 task package:windows:amd64

      - name: Build windows/arm64
        run: |
            wails3 task build:windows:prod:arm64
            wails3 task package:windows:arm64
        